project:
  type: website

website:
  title: "College Softball Analysis"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: story.qmd
        text: "Team Power"
      - href: models.qmd
        text: "Model & Impact"
      - href: exploration.qmd
        text: "Explore Teams"
      - href: hitters.qmd
        text: "Explore Hitters"
      - href: about.qmd
        text: "About"

format:
  html:
    theme: cosmo
    toc: true
